name: myapp

on: pusH
    

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
        matrix:
            on:[ubuntu-latest,windows,macOS-latest]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  
        
    - name: Install dependencies
      run: |
        make install 
        
    - name: test with pytest
      run: |
        make test
