name: app

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
   
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        
    - name: Install dependencies
      run: |
           run: pip3 install -r requirements.txt
        
    - name: Execute test cases
      run: |
          make test
